const DB_NAME='newsthinking', DB_VERSION=1;
const NEWS_BASE='https://raw.githubusercontent.com/eomjeongyun/newsthinking-feed/main/news';
const NEWS_KEY='1QjZFKqZSyo8qj9lkiHw9iSkmoCCxJ0idwUt5UZ//IA=';
const TOURISM_KEY='archive:andong-tourism';
const state={days:[],notes:[],tourism:[],tab:'today',date:null,category:'random',andongSub:'andongSociety',detail:null,online:true,month:null,search:''};
const app=document.querySelector('#app');

function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('days'))db.createObjectStore('days',{keyPath:'date'});if(!db.objectStoreNames.contains('notes'))db.createObjectStore('notes',{keyPath:'articleId'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function all(store){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function put(store,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dayByDate=date=>state.days.find(day=>day.date===date);
const noteById=id=>state.notes.find(note=>note.articleId===id);
function parseDate(value){const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d);}
function dateLabel(value,long=false){if(!value)return '';const d=parseDate(value);const week=['일요일','월요일','화요일','수요일','목요일','금요일','토요일'][d.getDay()];return long?`${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일 ${week}`:`${d.getMonth()+1}월 ${d.getDate()}일 ${week}`;}
function articleDate(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(d);}
function sections(day){return {random:{label:day?.random?.topic||'랜덤',articles:day?.random?.articles||[]},andongSociety:{label:'안동 사회',articles:day?.andong?.society||[]},andongTourism:{label:'안동 관광',articles:state.tourism}};}
function findArticle(date,id){const tourismArticle=state.tourism.find(a=>a.id===id);if(tourismArticle)return {article:tourismArticle,section:'andongTourism',label:'안동 관광'};const day=dayByDate(date),sets=sections(day);for(const [section,data] of Object.entries(sets)){if(section==='andongTourism')continue;const article=data.articles.find(a=>a.id===id);if(article)return {article,section,label:data.label};}const legacyTourism=day?.andong?.tourism?.find(a=>a.id===id);return legacyTourism?{article:legacyTourism,section:'andongTourism',label:'안동 관광'}:null;}
function setTab(tab){state.tab=tab;state.detail=null;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render();window.scrollTo(0,0);}
document.querySelector('.tabbar').addEventListener('click',e=>{const button=e.target.closest('[data-tab]');if(button)setTab(button.dataset.tab);});

function header(){return `<header class="page-head"><div><h1 class="brand">News Thinking</h1><p class="date-title">${esc(dateLabel(state.date))}</p></div>${state.online?'':`<span class="status">오프라인 · 저장된 뉴스</span>`}</header>`;}
function articleCards(items,date,isTourism=false){if(!items.length)return `<div class="empty">${isTourism?'모아둔 관광 기사가 아직 없어요.':'오늘은 이 분야의 뉴스가 아직 없어요.'}</div>`;return `<div class="article-list">${items.map(a=>`<button class="card" data-article="${esc(a.id)}" data-date="${esc(isTourism?a.addedAt:date)}"><strong class="card-title">${esc(a.title)}</strong>${a.subtitle?`<span class="card-subtitle">${esc(a.subtitle)}</span>`:''}<span class="meta">${a.origin==='dad'?'<span class="origin-label">아빠가 보내준 기사</span>':''}${esc(a.source||'출처 없음')}${noteById(a.id)?'<span class="note-mark">기록 있음</span>':''}</span></button>`).join('')}</div>`;}
function todayView(){const day=dayByDate(state.date),sets=sections(day),tourismSelected=state.category==='andong'&&state.andongSub==='andongTourism';let content;if(tourismSelected)content=`<div class="pills"><button class="subpill" data-sub="andongSociety">안동 사회</button><button class="subpill active" data-sub="andongTourism">안동 관광</button></div><div class="collection-count">모아둔 기사 ${state.tourism.length}개</div>${articleCards(state.tourism,state.date,true)}`;else if(!day)content='<div class="empty">저장된 뉴스가 아직 없어요.<br>연결되면 새 뉴스를 불러올게요.</div>';else if(state.category==='random')content=`<span class="topic-chip">오늘의 주제 · ${esc(sets.random.label)}</span>${articleCards(sets.random.articles,day.date)}`;else{content=`<div class="pills"><button class="subpill active" data-sub="andongSociety">안동 사회</button><button class="subpill" data-sub="andongTourism">안동 관광</button></div>${articleCards(sets.andongSociety.articles,day.date)}`;}
return `${header()}<div class="pills"><button class="pill ${state.category==='random'?'active':''}" data-category="random">랜덤</button><button class="pill ${state.category==='andong'?'active':''}" data-category="andong">안동</button></div>${content}${state.days.length&&state.date!==state.days.at(-1).date?'<button class="today-link" data-latest>최신 뉴스로 돌아가기</button>':''}`;}
function detailView(){const found=findArticle(state.detail.date,state.detail.id);if(!found)return `${header()}<div class="empty">이 기사를 찾을 수 없어요.</div>`;const {article,label}=found,note=noteById(article.id)||{};const paragraphs=String(article.body||'').split(/\n\s*\n/).filter(Boolean);return `<button class="back" data-back aria-label="기사 목록으로 돌아가기">‹ 기사 목록</button><div class="detail-label">${esc(label)}</div><h1 class="detail-title">${esc(article.title)}</h1>${article.subtitle?`<p class="detail-subtitle">${esc(article.subtitle)}</p>`:''}<div class="meta article-meta">${esc(article.source||'출처 없음')}${articleDate(article.publishedAt)?` · ${esc(articleDate(article.publishedAt))}`:''}</div>${article.note?`<p class="article-note">${esc(article.note)}</p>`:''}<article class="body">${paragraphs.length?paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''):'<p>기사 본문이 제공되지 않았어요.</p>'}</article><section class="writing"><label for="thought">나의 생각</label><textarea id="thought" data-note-field="thought" placeholder="기사를 읽고 떠오른 생각을 적어보세요.">${esc(note.thought||'')}</textarea><div class="saved" data-saved></div></section><section class="writing"><label for="insight">도출한 인사이트</label><textarea id="insight" data-note-field="insight" placeholder="앞으로 기억하거나 적용할 점을 적어보세요.">${esc(note.insight||'')}</textarea><div class="saved" data-saved></div></section>`;}
function calendarView(){const base=state.month||parseDate(state.date||new Date().toISOString().slice(0,10)),y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),available=new Set(state.days.map(d=>d.date)),noted=new Set(state.notes.map(n=>n.date)),today=new Date(),cells=[];for(let i=0;i<first;i++)cells.push('<button class="day blank" tabindex="-1"></button>');for(let d=1;d<=count;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells.push(`<button class="day ${available.has(key)?'available':''} ${state.date===key?'selected':''} ${today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d?'today':''}" data-day="${key}" ${available.has(key)?'': 'disabled'} aria-label="${m+1}월 ${d}일${noted.has(key)?', 기록 있음':''}">${d}${noted.has(key)?'<span class="dot"></span>':''}</button>`);}return `${header()}<div class="calendar-head"><button class="icon-btn" data-month="-1" aria-label="이전 달">‹</button><h2>${y}년 ${m+1}월</h2><button class="icon-btn" data-month="1" aria-label="다음 달">›</button></div><div class="week"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div class="calendar-grid">${cells.join('')}</div>`;}
function notesView(){const q=state.search.trim().toLowerCase(),notes=state.notes.filter(n=>!q||[n.title,n.thought,n.insight].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));const randomOrder=['사회','정치','경제','연예','국제','문화','IT·산업','스포츠'],groups=[['랜덤',randomOrder.map(label=>[label,notes.filter(n=>n.section==='random'&&n.subcategory===label)])],['안동',[['안동 사회',notes.filter(n=>n.section==='andongSociety')],['안동 관광',notes.filter(n=>n.section==='andongTourism')]]]];const html=groups.map(([title,subs])=>{const visible=subs.filter(([,items])=>items.length);return visible.length?`<section><h2 class="group-title">${title}</h2>${visible.map(([label,items])=>`<h3 class="sub-title">${esc(label)}</h3><div class="article-list">${items.map(n=>`<button class="card" data-article="${esc(n.articleId)}" data-date="${esc(n.date)}"><span class="archive-date">${esc(n.date)}</span><strong class="card-title">${esc(n.title)}</strong><span class="excerpt">${esc((n.thought||n.insight||'작성한 내용이 있어요.').split(/\r?\n/)[0])}</span></button>`).join('')}</div>`).join('')}</section>`:'';}).join('');return `<header class="page-head"><div><h1 class="brand">내 생각</h1><p class="date-title">차곡차곡 쌓인 기록</p></div>${state.online?'':`<span class="status">오프라인</span>`}</header><label for="search" class="meta">기록 검색</label><input id="search" class="search" type="search" value="${esc(state.search)}" placeholder="제목, 생각, 인사이트 검색">${html||'<div class="empty">아직 저장한 생각이 없어요.</div>'}`;}
function addSourceLink(){if(!state.detail)return;const found=findArticle(state.detail.date,state.detail.id),url=typeof found?.article?.url==='string'?found.article.url.trim():'';if(!url)return;const wrapper=document.createElement('div'),link=document.createElement('a'),label=document.createElement('small');wrapper.className='source-link';link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='기사 원문 보기 ↗';label.textContent=found.article.linkLabel||'원문 기사';wrapper.append(link,label);app.querySelector('.article-meta')?.after(wrapper);}
function render(){app.innerHTML=state.detail?detailView():state.tab==='today'?todayView():state.tab==='calendar'?calendarView():notesView();addSourceLink();bind();}
function grow(el){el.style.height='auto';el.style.height=`${Math.max(125,el.scrollHeight)}px`;}
let saveTimer;
function bind(){app.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render();});app.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{state.andongSub=b.dataset.sub;render();});app.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>{state.detail={id:b.dataset.article,date:b.dataset.date};state.date=b.dataset.date;render();window.scrollTo(0,0);});const back=app.querySelector('[data-back]');if(back)back.onclick=()=>{state.detail=null;render();};const latest=app.querySelector('[data-latest]');if(latest)latest.onclick=()=>{state.date=state.days.at(-1).date;render();};app.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{const base=state.month||parseDate(state.date);state.month=new Date(base.getFullYear(),base.getMonth()+Number(b.dataset.month),1);render();});app.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.date=b.dataset.day;state.tab='today';document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab==='today'));render();});const search=app.querySelector('#search');if(search)search.oninput=()=>{state.search=search.value;const pos=search.selectionStart;render();const next=app.querySelector('#search');next.focus();next.setSelectionRange(pos,pos);};app.querySelectorAll('textarea').forEach(el=>{grow(el);el.oninput=()=>{grow(el);app.querySelectorAll('[data-saved]').forEach(s=>s.textContent='저장 중…');clearTimeout(saveTimer);saveTimer=setTimeout(saveNote,500);};});}
async function saveNote(){const found=findArticle(state.detail.date,state.detail.id);if(!found)return;const thought=app.querySelector('#thought').value,insight=app.querySelector('#insight').value,{article,section,label}=found;const note={articleId:article.id,date:section==='andongTourism'?(article.addedAt||state.detail.date):state.detail.date,section,subcategory:label,title:article.title,thought,insight,updatedAt:new Date().toISOString()};await put('notes',note);const i=state.notes.findIndex(n=>n.articleId===note.articleId);if(i>=0)state.notes[i]=note;else state.notes.push(note);app.querySelectorAll('[data-saved]').forEach(s=>s.textContent='저장됨');}
function base64Bytes(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
async function fetchJSON(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('offline');return response.json();}
async function decryptDay(envelope){if(envelope?.v!==1||envelope.alg!=='AES-GCM'||typeof envelope.iv!=='string'||typeof envelope.ct!=='string')throw new Error('invalid');const iv=base64Bytes(envelope.iv),ct=base64Bytes(envelope.ct);if(iv.length!==12||ct.length<=16)throw new Error('invalid');const key=await crypto.subtle.importKey('raw',base64Bytes(NEWS_KEY),{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct);return JSON.parse(new TextDecoder().decode(plain));}
function validDay(day,date){if(!day||day.date!==date||typeof day.generatedAt!=='string'||typeof day.random?.topic!=='string'||!Array.isArray(day.random?.articles)||!Array.isArray(day.andong?.society)||!Array.isArray(day.andong?.tourism))return false;return day.random.articles.length+day.andong.society.length+day.andong.tourism.length>0;}
function validTourism(data){return data&&Array.isArray(data.items)&&data.items.length>0&&typeof data.updatedAt==='string'&&data.items.every(item=>item&&typeof item.id==='string'&&typeof item.title==='string'&&typeof item.addedAt==='string');}
async function syncTourism(){const envelope=await fetchJSON(`${NEWS_BASE}/andong_tourism.json?t=${Date.now()}`),data=await decryptDay(envelope);if(!validTourism(data))throw new Error('invalid');const items=data.items.map((item,index)=>({...item,_order:index})).sort((a,b)=>b.addedAt.localeCompare(a.addedAt)||a._order-b._order).map(({_order,...item})=>item);await put('days',{date:TOURISM_KEY,items,updatedAt:data.updatedAt});state.tourism=items;}
async function syncDays(){const previousLatest=state.days.at(-1)?.date,wasLatest=!state.date||state.date===previousLatest,index=await fetchJSON(`${NEWS_BASE}/index.json?t=${Date.now()}`);if(!Array.isArray(index?.dates))throw new Error('invalid');const stored=new Set(state.days.map(d=>d.date)),today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});let complete=true;for(const date of index.dates){if(typeof date!=='string'||(stored.has(date)&&date!==today))continue;try{const envelope=await fetchJSON(`${NEWS_BASE}/${encodeURIComponent(date)}.json${date===today?`?t=${Date.now()}`:''}`),day=await decryptDay(envelope);if(!validDay(day,date))throw new Error('invalid');await put('days',day);const i=state.days.findIndex(d=>d.date===date);if(i>=0)state.days[i]=day;else state.days.push(day);}catch(_error){complete=false;}}state.days.sort((a,b)=>a.date.localeCompare(b.date));if(wasLatest&&state.days.length)state.date=state.days.at(-1).date;if(!complete)throw new Error('incomplete');}
async function sync(){const results=await Promise.allSettled([syncDays(),syncTourism()]);state.online=results.every(result=>result.status==='fulfilled');render();}
async function init(){try{const [records,notes]=await Promise.all([all('days'),all('notes')]),archive=records.find(record=>record.date===TOURISM_KEY);state.days=records.filter(record=>record.date!==TOURISM_KEY);state.tourism=Array.isArray(archive?.items)?archive.items:[];state.notes=notes;state.days.sort((a,b)=>a.date.localeCompare(b.date));if(state.days.length)state.date=state.days.at(-1).date;state.month=state.date?parseDate(state.date):new Date();render();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});sync();}catch(_error){state.online=false;render();}}
if('serviceWorker'in navigator)window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})});
init();

// Best-effort daily backup to the home server: silently skipped when the PC is off, retried next time the app opens.
async function dailyBackup(){try{const today=new Date().toISOString().slice(0,10);if(localStorage.getItem('nt-backup-date')===today)return;const [days,notes]=await Promise.all([all('days'),all('notes')]);const res=await fetch('https://appointee-unnoticed-donated.ngrok-free.dev/api/app-backup/newsthinking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({days,notes})});if(res.ok)localStorage.setItem('nt-backup-date',today)}catch(e){}}
setTimeout(dailyBackup,3000);
